feat: add hacknitr4 certificates
dscnitrourkela/project-guava-web pull request #95
Opened 2023-04-11 13:16 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-04-18 16:26 UTC, ORKO06 approved these changes

2023-04-30 01:19 UTC, ORKO06 commented
@abhibhaw @riteshsp2000 
Can you please merge this PR?

2023-04-30 10:13 UTC, abhibhaw requested changes

2023-04-30 10:13 UTC, abhibhaw commented on client/src/screens/ViewCertificate.tsx
> +        : 'https://res.cloudinary.com/ashishpadhy/image/upload/v1681215343/avupszlcs4j936xg0zaw.png'
Both the certificates are same!!

2023-05-09 10:03 UTC, abhibhaw approved these changes
LGTM

2023-05-09 10:05 UTC, merged